### ISSUE TITLE
Failed to start virtual machine on Windows

### ISSUE THREAD

**Issue by bwayne** [oscar-stack/vagrant-auto_network#3]
Hi,

I tried to run `vagrant up` and got this backtrace:

```
C:\Users\user\git\conduit>vagrant up
Bringing machine 'conduit-dev.local' up with 'virtualbox' provider...
[conduit-dev.local] Importing base box 'centos-64-x64-vbox4210-nocm'...
[conduit-dev.local] Matching MAC address for NAT networking...
[conduit-dev.local] Setting the name of the VM...
[conduit-dev.local] Clearing any previously set forwarded ports...
[conduit-dev.local] Creating shared folders metadata...
[conduit-dev.local] Clearing any previously set network interfaces...
[conduit-dev.local] Destroying VM and associated drives...
[conduit-dev.local] Running cleanup tasks for 'hosts' provisioner...
[conduit-dev.local] Running cleanup tasks for 'pe_bootstrap' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
[conduit-dev.local] Running cleanup tasks for 'shell' provisioner...
C:/Users/bwayne/.vagrant.d/gems/gems/vagrant-auto_network-0.2.1/lib/auto_network
/action_helpers.rb:10:in `machine_has_address?': undefined method `address_for'
for false:FalseClass (NoMethodError)
        from C:/Users/bwayne/.vagrant.d/gems/gems/vagrant-auto_network-0.2.1/lib
/auto_network/action/request.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/clear_network_interfaces.rb:26:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/share_folders.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/clear_shared_folders.rb:12:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/prepare_nfs_settings.rb:11:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/nfs.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/prune_nfs_exports.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/handle_forwarded_port_collisions.rb:118:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/env_set.rb:19:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/provision.rb:54:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/set_name.rb:47:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/clean_machine_folder.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/u
til/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/u
til/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/u
til/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/call.rb:57:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builtin/call.rb:57:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/provi
ders/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/Users/bwayne/.vagrant.d/gems/gems/vagrant-pe_build-0.8.1/lib/pe_
build/action/pe_build_dir.rb:16:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/Users/bwayne/.vagrant.d/gems/gems/vagrant-auto_network-0.2.1/lib
/auto_network/action/load_pool.rb:26:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/u
til/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/a
ction/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/m
achine.rb:147:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/b
atch_action.rb:63:in `block (2 levels) in run'
```

Any idea what's happening here? Thanks!

**Comment by Sharpie** [comment]
Closing as this bug relates to auto_network 0.2.1. Please open a new ticket if the issue still occurs on a 1.x version.
