### ISSUE TITLE
Psych/YAML parse error 

### ISSUE THREAD

**Issue by bryanzera-wbez** [oscar-stack/vagrant-auto_network#33]
My machine (OS X 10.10.5) crashed when starting Vagrant 1.7.2 on Ruby 2.0.0p481.  When it came back up, this error occurs if I try to start a vagrant whose config includes an `auto_network` setting:

    /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 288 column 7 (Psych::SyntaxError)
        from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:153:in `parse'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:129:in `load'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/yaml/store.rb:61:in `load'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/pool_storage.rb:73:in `load'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/pstore.rb:395:in `load_data'
        from /opt/vagrant/embedded/lib/ruby/2.0.0/pstore.rb:327:in `transaction'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/pool_manager.rb:41:in `with_pool_for'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/pool_manager.rb:74:in `address_for'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/action/base.rb:37:in `machine_has_address?'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/action/filter_networks.rb:31:in `block in filter'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/action/filter_networks.rb:30:in `each'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/action/filter_networks.rb:30:in `filter'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/action/filter_networks.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /Users/bryanzera/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/action/load_pool.rb:19:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in `hook'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:187:in `initialize'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:165:in `new'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:165:in `<main>'

Disabling the auto_network setting allows the machine to start.

**Comment by IvanChepurnyi** [comment]
The same issue happened to me, I got auto_network pool.yaml file corrupted somehow, for unknown reason. 
Edit the pool file at this location and remove strange characters, that helped me. 
nano ~/.vagrant.d/auto_network/pool.yaml
